# Generated by Django 6.1.1 on 2026-09-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('srcaddr', models.CharField(blank=True, max_length=255, null=True)),
                ('dstaddr', models.CharField(blank=True, max_length=255, null=True)),
                ('srcport', models.IntegerField(blank=True, null=True)),
                ('dstport', models.IntegerField(blank=True, null=True)),
                ('protocol', models.IntegerField(blank=True, null=True)),
                ('packets', models.IntegerField(blank=True, null=True)),
                ('bytes', models.IntegerField(blank=True, null=True)),
                ('starttime', models.BigIntegerField(blank=True, null=True)),
                ('endtime', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('log_status', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
